# Generated by Django 5.2.1 on 2025-05-19 11:00

import django.db.models.deletion
import panphoto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panphoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramamarker',
            name='linked_panorama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_markers', to='panphoto.panorama', verbose_name='Связанная панорама'),
        ),
        migrations.AlterField(
            model_name='panoramamarker',
            name='latitude',
            field=models.FloatField(verbose_name='Широта (-90° до 90°)'),
        ),
        migrations.AlterField(
            model_name='panoramamarker',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота (0-360°)'),
        ),
        migrations.AlterField(
            model_name='panoramamarker',
            name='panorama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='panphoto.panorama', verbose_name='Базовая панорама'),
        ),
        migrations.AlterField(
            model_name='panoramamarker',
            name='size',
            field=models.JSONField(default=panphoto.models.default_marker_size, verbose_name='Размер (в пикселях)'),
        ),
        migrations.AlterField(
            model_name='panoramamarker',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст метки'),
        ),
    ]
