# Generated by Django 5.2.1 on 2025-05-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panphoto', '0002_panoramamarker_linked_panorama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoramamarker',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст тултипа маркера'),
        ),
    ]
