# Generated by Django 5.2.1 on 2025-05-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panphoto', '0004_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramamarker',
            name='pitch',
            field=models.FloatField(default=0, verbose_name='Вертикальный угол (вверх/вниз) (-Pi/2 .. +Pi/2).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panoramamarker',
            name='yaw',
            field=models.FloatField(default=0, verbose_name='Горизонтальный угол (влево/вправо) (-Pi .. +Pi).'),
            preserve_default=False,
        ),
    ]
