# Generated by Django 5.2.1 on 2025-05-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panphoto', '0005_panoramamarker_pitch_panoramamarker_yaw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panoramamarker',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='panoramamarker',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='panoramamarker',
            name='size',
        ),
    ]
